list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}")
list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/sdk")

include(common)
# message("CMAKE_MODULE_PATH: ${CMAKE_MODULE_PATH}")

# if (NOT DEFINED ESP8266_SDK_VARIANT OR ESP8266_SDK_VARIANT STREQUAL "")
#     message(FATAL_ERROR "ESP8266_SDK_VARIANT has not been defined")
# endif ()
# 
# if (NOT DEFINED ESP8266_SDK_VERSION OR ESP8266_SDK_VERSION STREQUAL "")
#     message(FATAL_ERROR "ESP8266_SDK_VERSION has not been defined")
# endif()


include(OPENRTOS)
